# Generated by Django 5.1.15 on 2026-09-25 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leafKg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='鲜叶千克(kg)')),
                ('receivedAt', models.DateTimeField(verbose_name='签收时刻')),
                ('supplierVillage', models.CharField(max_length=120, verbose_name='供货村名')),
                ('receiver', models.CharField(max_length=80, verbose_name='签收人')),
                ('isReversed', models.BooleanField(default=False, verbose_name='已冲销')),
                ('reversedAt', models.DateTimeField(blank=True, null=True, verbose_name='冲销时刻')),
                ('reversedBy', models.CharField(blank=True, default='', max_length=80, verbose_name='冲销人')),
                ('trough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='gardens.trough', verbose_name='所属槽位')),
            ],
            options={
                'verbose_name': '鲜叶签收',
                'verbose_name_plural': '鲜叶签收',
                'ordering': ['-receivedAt', '-id'],
            },
        ),
    ]
